// Generated by CoffeeScript 1.4.0

/*
Sticky Elements Shortcut for jQuery Waypoints - v2.0.2
Copyright (c) 2011-2013 Caleb Troughton
Dual licensed under the MIT license and GPL license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/


(function() {

  (function(root, factory) {
    if (typeof define === 'function' && define.amd) {
      return define(['jquery', 'waypoints'], factory);
    } else {
      return factory(root.jQuery);
    }
  })(this, function($) {
    var defaults, wrap;
    defaults = {
      wrapper: '<div class="sticky-wrapper" />',
      stuckClass: 'stuck'
    };
    wrap = function($elements, options) {
      $elements.wrap(options.wrapper);
      $elements.each(function() {
        var $this;
        $this = $(this);
        $this.parent().height($this.outerHeight());
        return true;
      });
      return $elements.parent();
    };
    return $.waypoints('extendFn', 'sticky', function(options) {
      var $wrap, originalHandler;
      options = $.extend({}, $.fn.waypoint.defaults, defaults, options);
      $wrap = wrap(this, options);
      originalHandler = options.handler;
      options.handler = function(direction) {
        var $sticky, shouldBeStuck;
        $sticky = $(this).children(':first');
        shouldBeStuck = direction === 'down' || direction === 'right';
        $sticky.toggleClass(options.stuckClass, shouldBeStuck);
        if (originalHandler != null) {
          return originalHandler.call(this, direction);
        }
      };
      $wrap.waypoint(options);
      return this;
    });
  });

}).call(this);


$(document).ready(function() {
    $('#menu').waypoint('sticky');

    $('#wrapper > section').waypoint(function(event, direction) {

      var $active = $(this);

      if (direction === "up") {
        $active = $active.prev();
      }

      if (!$active.length) $active = $active.end();
      
      $('.link-active').removeClass('link-active');
      $('a[href=#'+$active.attr('id')+']').addClass('link-active');

    });
  
    $(".day-title-one").click(function() {
      $(".day-title-one").parent().removeClass("day-two");   
      $(this).parent().addClass("day-one");
    });

    $(".day-title-two").click(function() {
      $(".day-title-two").parent().removeClass("day-one");   
      $(this).parent().addClass("day-two");
    });


    // Modal
    
    $('#read-more-1, #read-more-2, #read-more-3, #read-more-4, #read-more-5, #read-more-6, #read-more-7, #read-more-8, #read-more-9, #read-more-10, #read-more-11, #read-more-12, #read-more-13, #read-more-14').click(function(){
      $(this).closest('.event').find('.modal-container').show();
      $('.modalBg').show();
    });

    $('#read-less-1, #read-less-2, #read-less-3, #read-less-4, #read-less-5, #read-less-6, #read-less-7, #read-less-8, #read-less-9, #read-less-10, #read-less-11, #read-less-12, #read-less-13, #read-less-14').click(function(){
      $(this).closest('.event').find('.modal-container, .modalBg').hide();
      $('.modalBg').hide();
    });

    $(".modalBg").click(function() {
      $('.modal-container').hide();
      $('.modalBg').hide();
    });


  });

